### ISSUE TITLE
C# native language support

### ISSUE THREAD

**Issue by Febbie15** [browserup/mitmproxy#9]
**C# native language support for MITM Proxy** will be very useful for us as per our project requirement. As alternate option, we
planned to use REST API in our code, but when I click the document link, it shows 404 (Page not available) error. Kindly help me out.

**Comment by ericbeland** [comment]
We don't have any plans to support C# in the near-term. No one who works on this has C# installed.

There is possibly a way to get some C# support if you want to invest a bit of time. We generate all of our API clients using a tool called OpenAPI generator. The instructions to generate clients are here:

https://github.com/browserup/mitmproxy/tree/main/clients

If you were to create a config for C# and run the generator, you could probably generate a good C# client.

If you create a working C# config, we would accept a PR for at least the config, although maybe not the whole client since we don't have  a testing setup for that.

**Comment by ericbeland** [comment]
Can you point me to the broken link you mentioned?

**Comment by Febbie15** [comment]
Thanks for your quick response. We will analyze your suggestions to support C# config and come back. This is the broken link https://github.com/browserup/mitmproxy/blob/main/doc.html.
